### ISSUE TITLE
plug in the 2005 version Weimer in WAM 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/WAM-IPE#284]
After the validation of the neutral temperature during the 2013 and 2015 St. Patrick storms. We found that the Temp. is pretty high (about 3000k at around 250km) at the peak storm time, especially at high latitude and polar region. While the neutral temp. with our new Joule heating factors during quite time are pretty reasonable against MSIS output based on our validation.    We plan to plug-in the new version Weimer (2005) in WAM to bring in the saturation mechanism to control the high peak neutral temp in the current runs.

**Comment by ZhuxiaoLi66** [comment]
Testing and getting familiar with the codes of Weimer 2005 and the input files which grabbed from CTIPe by Mariangle. 
The first step is given the dummy values to the several input variables (angle, bt, tilt, swvel, swden) with the original grids to get a basic electric potential distribution pattern.

**Comment by ZhuxiaoLi66** [comment]
We got an reasonable electric potential pattern over North Hemisphere by the  Weimer_2005 package.
 with the following parameters value setting, 
angle= 123.255, bt= 4.3368, swvel=343.66
swden= 5.0, tilt  = 28.0
![EPOT_Polar_Weimer2005_CIPTe_grid_test](https://user-images.githubusercontent.com/22546571/55898273-c42af780-5bb1-11e9-9355-303bbc9a4669.png)

**Comment by ZhuxiaoLi66** [comment]
the above output based on CTIPe grids. please also ignore the longitude notation in the above plot, since we don't transform the geomagnetic frame into geography frame. The boarder latitude of the above plot is N48. 
Next step is plug in the new Weimer package in an downloaded independent code of efield.f from the tip WAM branch.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk would like you know that we need the new driving parameter of swden (solar wind density) to get the new Weimer codes work in WAM. maybe also need your great helps on other aspects later.

**Comment by akubaryk** [comment]
What's the timeline on this? The swden code is (mostly) available already in the input parameter parsing scripts, just need to uncomment some lines. The "calculate from other parameters" option simply sets it to 5.0. Adding the read in to the model shouldn't be too tough. Let me know how quickly you're looking to run with this and I can carve out some time to make a branch.

**Comment by ZhuxiaoLi66** [comment]
Thanks, Adam. it is a current main task of the WAM development on my side. it is expected to solve the too high temp issue in the intense storm runs.  If you could find time to do it next week, it will be very helpful. otherwise, I will set swden=5 as a parameter in the test run.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk To get the new Weimer package works, we also need to put several text input files (all constant coefficient files during any runs, never change) in somewhere for the Weimer code to read in, they are in my Theia DIR Theia: /scratch3/NCEPDEV/swpc/save/Zhuxiao.Li/git/Weimer/Coef_input

The current Weimer in WAM supposed to read in a similar coefficient file named 'global_idea_wei96.cofcnts' which I didn't find where it is (seems nowhere!). 

Do you think it is good to put the text files in a similar place of 'wam_f107_kp_mod.txt' is a good idea? 
how to let the model find and read them? we supposed can use ./phys/idea_io_units.f? or used your way like get wam_f107_kp_mod.txt in? Could you please use your expertise to help me to make the files available for WAM phys?  NEMS/src/atmos/phys/efield.f supposed to read these files. 
If it could be done with the swden input work, it will be perfect. By the way, takes your time and maybe the WAM test runs will begin kind of later than next weekend. Thanks a lot in head!

**Comment by ZhuxiaoLi66** [comment]
@akubaryk I found the input files of global_idea_wei96.cofcnts, global_idea_coeff_hflux.dat, global_idea_coeff_lflux.dat needed by current Weimer in my run directory, thanks for Naomi's reminder.  
While still need to figure out how the path is setting though the scripts.

**Comment by akubaryk** [comment]
The coefficient files are here: /scratch4/NCEPDEV/nems/noscrub/emc.nemspara/RT/WAM-IPE/WAM-IPE_NEMS201606-20170302/data/WAM_gh_l150/

this is a "hard-coded" path for each system set in $FMID.config, for example theia.config contains:

`export DATADIR=${DATADIR:-/scratch4/NCEPDEV/nems/noscrub/emc.nemspara/RT/WAM-IPE/WAM-IPE_NEMS201606-20170302/data}`

and then in nems.config:
`export FIX_IDEA=${FIX_IDEA:-$DATADIR/WAM_gh_l150} # global_idea* fix files`

and then in exglobal_fcst_nems.sh
`${NLN} $FIX_IDEA/global_idea* .`

So we can either define a new path to link in the coefficient file, or we can get someone(?) to add the new coefficient file to nems path where the coefficient files are currently pulled from.

**Comment by ZhuxiaoLi66** [comment]
Thanks for the very helpful information, Adam. I think maybe it is neat to put the new input files into the nems path where the coefficient files currently in and even change their name in global_idea something.
Your question mark means we need some copyrights to put the files in that directory?

**Comment by ZhuxiaoLi66** [comment]
In that way, maybe we need to define a new temporary path. who we suppose to contact with?

**Comment by akubaryk** [comment]
Someone with emc.nemspara access, probably Jun Wang, but not 100% sure on that.

**Comment by ZhuxiaoLi66** [comment]
Got it, thanks. I will try to contact with Jun Wang, at least we can get some clue on it. 
As for the new path, it is ease for you to define? just follow your above flow?

**Comment by akubaryk** [comment]
drop `export WEIMER_FIX=${WEIMER_FIX:-/default/path/on/theia}` in theia.config, and then in exglobal you can `${NLN} $WEIMER_FIX/name_of_fix_file .`

**Comment by ZhuxiaoLi66** [comment]
Got it, thanks. Will try later.

**Comment by akubaryk** [comment]
You can `git pull origin swden` to get f91f1cbc273393567844f1fadc67e13582c2b21e into whatever local branch you're working from.

I did a WAM-IPE build test and ran 1hr with `export INPUT_PARAMETERS=timeobs` to make sure that it is running with the new parameter. Let me know if you have any questions.

**Comment by ZhuxiaoLi66** [comment]
Thanks, Adam. Will try when the code is ready.

**Comment by ZhuxiaoLi66** [comment]
![EPOT_Polar_Weimer2005_WAM_grid_test](https://user-images.githubusercontent.com/22546571/56157674-9a0d7700-5faf-11e9-9ac9-3bac9910e3a5.png)

**Comment by ZhuxiaoLi66** [comment]
the above plot is the electric potential on WAM grid by the new weimer codes. will check the problem and fix it.

**Comment by ZhuxiaoLi66** [comment]
https://drive.google.com/drive/u/0/folders/1N_-2WM3LftI5HRxuRjxuccFISUodDdMk

**Comment by ZhuxiaoLi66** [comment]
last week, we have got the consistent potential pattern by new Weimer package over the CTIPe grid and over the WAM gird after I reproduce the codes.
![EPOT_Polar_Weimer2005_CTIPe_grid_tilt0.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdb3a683e8ad7c9358f9992c54752379519c0844acd32d804569080b300af51d1c5f56e0ebc969f9ec6923ce4e01ffd43f5f71ce3b44fded8449ed02ee208b4ed6e3e88a4bc6e02f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee4485ca01a336aef723e7f55d9.png)
![EPOT_Polar_Weimer2005_WAM_grid_180.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdb3a683e8ad7c9358f9992c54752379519c1c51a8dc2fad4b7f3e5e574ebe5d4a1f06a3a3dc78e2a436628f0e0be8d96b0a25933b47febbd61fbf00e975df4f82b0b49850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecd5dff4fe84b54a2103361f43b.png)

**Comment by ZhuxiaoLi66** [comment]
Now the 'stand along' efield.f code can call the new Weimer module and calculate the potential.  
The following is the potential calculated by the old and new Weimer package called by the 'stand alone' efield.f. 
The input parameters: By=0., Bz= 1.77, swvel= 450.,  swden=5.  
                        equal        :  Bt = 1.77, angle = 0., swvel = 450., swden=5., tilt = 0.
![EPOT_NH_efield_old_Weimer_WAM_grid.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdad81b0ecb94aa151f4ab264a234c1e01aa267597dc1f9e6f44061d061abe5d4a1f06a3a3dc78e2a436628f0e0be8d96b0a25933b47febbd61fbf00e975df4f82b0b49850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5dff4ee94b5ca2133e6bf43b.png)
![EPOT_NH_efield_Weimer2005_WAM_grid.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdad81b0ecb94aa151f4ab1e432e7e2c16f17b20d0dc1f9e6f44061d061abe5d4a1f06a3a3dc78e2a436628f0e0be8d96b0a25933b47febbd61fbf00e975df4f82b0b49850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5dff4ee94a55a1143065f43b.png)

**Comment by ZhuxiaoLi66** [comment]
The corresponding Potential calculated by the new Weimer code along is almost the same
![EPOT_Polar_Weimer2005_WAM_grid_pot_only_nofill_para_180.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdb3a683e8ad7c9358f9992c54752379519c1c51a8dc2fad4b7f3e1f000ac31e06030d93a7d67dffea601fca0d49bcbe6c5774d42103ecfadd45ea52fe32815d80e4bc8f44c6bd6c70e1dddd4c6a1e0519daaa0935a79f43da44e409b01301fb4e6f29b334247655961e7f2d6e6223a2f9d75f858063a7bc0262.png)
![EPOT_Polar_Weimer2005_WAM_grid_pot_only_nofill_180.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdb3a683e8ad7c9358f9992c54752379519c1c51a8dc2fad4b7f3e1f000ac31e06030d93a7d67dffea601f8b540bffcd7f1f36996744fffc9015ad04e8208e4783e3eddf4a96ba3e71e78b8e1c6b4a051f8ff74f29b2db1a960ca916b80700e6013c71e4773c7d42911b7c29636e25acf5de5695c8.png)

**Comment by ZhuxiaoLi66** [comment]
The corresponding potential plots for the top two panel of above comment, except with the same color_bar.
![EPOT_NH_efield_Weimer1996_WAM_grid_cb.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdad81b0ecb94aa151f4ab1e432e7e2c16f27229d3dc1f9e6f44061d061ac3120a4d58eeb9cb74fce36f34985619e8836d5a7cc06840f9bed44dbc55ba208a1cd0e2bc8d4ac8fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee74d50a3103167e67e356e0a.png)
![EPOT_NH_efield_Weimer2005_WAM_grid_cb.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cda4b517bdad81b0ecb94aa151f4ab1e432e7e2c16f17b20d0dc1f9e6f44061d061ac3120a4d58eeb9cb74fce36f34985619e8836d5a7cc06840f9bed44dbc55ba208a1cd0e2bc8d4ac8fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee74d50a3103167e6713f6e0a.png)

**Comment by ZhuxiaoLi66** [comment]
ED1 and ED2 electric fields by Weimer1996 .vs. Weimer2005 called from the indep. efield.f.
with by= 3.0, bz=1.77, swvel=450., swden=5.0
![ED1_ED2_NH_efield_WAM_Weimer1996_2005_by_3.0.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cdb0cb1ca7a7fbb0c7977ca15bf9912542184408299c1c758cee2dad13225859304cac415d3016b5968a35a6a42062ca1e54b7843e1b66cc2f14feb88717b954eb758d19d7b5e88a4cc1bb6871e78c89472c02175ad8a1096afdc0019d1ae441f34c52ae123366e076337b41971f732569756b.png)

**Comment by ZhuxiaoLi66** [comment]
with by= 0., bz=1.77, swvel=450., swden=5.0
The ED1 pattern looks a bit odd,
![ED1_ED2_NH_efield_WAM_Weimer1996_2005_cb.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cdb0cb1ca7a7fbb0c7977ca15bf9912542184408299c1c758cee2dad13225859304cac415d3017aeeb9539e6f4632adf0f4fffdb7f5a26c63819aaedd34ab957e823df4f85b7efdf18c0ef3b2df5979d0d6f405147d4a61760e28b41da59f141e04850a2133364ee733f7f40910c38.png)

**Comment by ZhuxiaoLi66** [comment]
@akubaryk I also pull the swden branch, did the 2days swin run, compared the corresponding run by development branch, sure got the bit by bit outputs. 
I also checked the wam_input_f107_kp.txt for the swden run, it nicely produced the swden input. will do the new weimer calling run soon.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk will ask Tim's help on checking the swden values especially during storm time for future pull request.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk I just pushed a new branch 'new_weimer' on Github based on your swden branch.  Actually, the compiling has been failed with the attached error message, seems your expertise can help me. 
I just added the new weimer module in NEMS/src/atmos/phys/ and make the efield.f call it. 
it complained the makefile in the same directory, while I did changed it...  could you have a look for me? Thanks in ahead!

![err_swden_new_weimer_compile.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46ed86881c9194ad8ae7804da14acf832c4f2a763b3ba0247d95ea24ba0037431f1d11f6140b1b56f6eb8c79a6b33476df0d5eeb873f5c20c63d10ffedd61fb807b232975dc7e7e2de139db17770a599855d3f190f198cfa5b37a39949c95bf548e25f18.png)

**Comment by akubaryk** [comment]
There were trailing spaces in the makefile on the line for the new file, which is not allowed.

w05sc_efield_merge.f also needed to be converted to fixed-format Fortran, and I cleaned up a little bug with the removal of the filepath from the SetModel_new call.

I've pushed these fixes (4e6522366727c4e5f695840be1db011d18d11a16) to the same branch that you can get with `git pull origin new_weimer`. I also removed the depend file in the same phys directory -- those are created by the make system and should probably be in the .gitignore file, but we don't want them in the repository either way. When we do a pull request on this branch, we'll want to merge these commits (and any future ones, probably).

**Comment by ZhuxiaoLi66** [comment]
Hi Adam, thanks very much for the great help! will pull it down and have a look and try!

**Comment by ZhuxiaoLi66** [comment]
by the way, I doubted the depend file... thanks anyway!

**Comment by ZhuxiaoLi66** [comment]
As for the pull request, maybe we need do it respectively, it has been found that there is some issues in the old e-field.f which calls the new weimer code. 
I will check the print out the swden values in efield.f in WAM, if it match the parameter files, the branch should be considered to be verified. talk later.

**Comment by ZhuxiaoLi66** [comment]
Hi Adam, I went though the code you revised, it is a lot of work, I do appreciate your great help! 
Could you please tell me how you got a fixed-format code for the w05sc_efield_merge.f, there is software or you manually did it (too much!)? and excuse me for the careless mistake of 'file_location'.

**Comment by akubaryk** [comment]
No problem, just did a regex find and replace on `^  ` to `^      ` -- did 95% of the work right there. Then some line continuations had to be altered, but there weren't that many, so they were done by hand.

**Comment by ZhuxiaoLi66** [comment]
Got it, many thanks!

**Comment by ZhuxiaoLi66** [comment]
As showed above, the new_weimer branch are pushed on Github with the great help of Adam. 
Now several runs have been submitted to do the validation of the new branch. 
At the same time, we will keep working on the individual efield.f & weimer2005 merge codes, since after the further validation and the investigation on the problem showed in the above plots, we found that there is some problem in the efield.f code in the current WAM, maybe also IPE?

**Comment by ZhuxiaoLi66** [comment]
The following plots are the electric potential as the output from efield.f for both Weimer1996 call and Weimer2005 call, the left panel is the output right after calling the Weimer EpotVal subroutine, the right panel is the output after the highlat_adjust, interpolation and smooth. 
The input parameters: by=0, bz=1.77, v_sw= 450, swden=5. 
![EPOT_efield_old_Weimer_EpotVal_DerivP](https://user-images.githubusercontent.com/22546571/56916653-ee811e00-6aa8-11e9-8b91-330d750be667.png)

![EPOT_efield_Weimer2005_EpotVal_DerivP](https://user-images.githubusercontent.com/22546571/56916665-f9d44980-6aa8-11e9-8ed4-6c35a282984d.png)

**Comment by ZhuxiaoLi66** [comment]
For the case by=3.0, bz=1.77, v_sw= 450, swden=5. the results seems much better.

![Epot_Weimer2005_efield_by3](https://user-images.githubusercontent.com/22546571/56916842-723b0a80-6aa9-11e9-9d94-011c706e77cd.png)

**Comment by ZhuxiaoLi66** [comment]
The following plot shows the electric potential (in case of by=0.) after each processing subroutine in efield.f after produced by calling EpotVal in new Weimer.  EP decreases a lot after subroutine highlat_adjust and sub interpolation.

![EPOT_efield_new_Weimer_each_sub_by0](https://user-images.githubusercontent.com/22546571/56917413-f215a480-6aaa-11e9-8ec7-69016e04aa44.png)

 For case by=3.0, results are much more reasonable.
![EPOT_efield_new_Weimer_each_sub_by3](https://user-images.githubusercontent.com/22546571/56917497-28532400-6aab-11e9-8906-a1f4ca86097a.png)

**Comment by ZhuxiaoLi66** [comment]
After investigated the subroutine code in efield, I think maybe there is some thing wrong in subroutine highlat_bnd before the highlat_adjust for the case by=0. 
The following is the ihlat_bnd output from highlat_bnd. 
 ihlat_bnd=           15          15          15          15          15
          15          14          14          14          14          11
          11          11          11          11          11          11
          11          11           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
          10          10          10          11          11          11
          11          11          11          11          11          11
          11          11          11          11          13          13
          13          13          13          13          14          14
          14          14          14          14          14          13
          13          13          13          13          13          13
          13          13          13          13          13          13
          13          13          13          13          13          13
          13          13          13          13          13          13
          13          13          13          13          13          13
          13          13          13          13          13          13
          13          13          13          13          13          13
          13          14          14          14          14          14
          14          14          14          14          14          14
          14          14          14          14          14          14
          14          14          14          14          14          15
          15          15          15          15          15          14
          14          14          14          14          14          14
          14          14          14          14          14          14
          14          14          14          14          14          14
          14          14          15          15          15          15
          15          15          15          15          15          15
          15          15          15          15          15          15
          15          15          15          15          15          15
          15          15

**Comment by ZhuxiaoLi66** [comment]
The following plot shows the electric potential (bz=20. & by=3.) after each processing subroutine in efield.f after produced by calling EpotVal in new Weimer.

![potent_by3_bz20_each_sub_efield](https://user-images.githubusercontent.com/22546571/56990729-5e64d680-6b85-11e9-80e1-cc497b8a7d80.png)

**Comment by ZhuxiaoLi66** [comment]
For storm case, with by= 3.0, bz=-20., swvel=450., swden=5.0

![ed1_ed2_bz-20_by3_weimer_efield](https://user-images.githubusercontent.com/22546571/56996161-34b2ac00-6b93-11e9-9629-bb506da9e7c0.png)

![potent_by3_bz-20_each_sub_efield](https://user-images.githubusercontent.com/22546571/56996174-41370480-6b93-11e9-9f1d-b13195bc53c1.png)

**Comment by ZhuxiaoLi66** [comment]
Good news. Based on the new storm runs by the new_weimer WAM branch (developed from Adam's swden branch),  we can see the neutral temperature at high level in WAM has dramatically decreased at the storm peak time due to the calling of the new Weimer package by efield.f code in WAM phys dir.

The following plots are the comparison of the Temp. at Lev135 between the new_weimer run and the tip WAM run for St. Patric storm of 2015. 

![T_wind_2D_WAM_new_Weimer_swden_20150316_4p](https://user-images.githubusercontent.com/22546571/57106535-28f2f100-6d1d-11e9-981f-eb0fbf52ecf2.png)

![T_wind_2D_WAM_jdel8_compiler_20150316_4p_cb](https://user-images.githubusercontent.com/22546571/57106553-3c05c100-6d1d-11e9-9113-4edbdac2309b.png)

![T_wind_2D_WAM_new_Weimer_swden_20150317_4p](https://user-images.githubusercontent.com/22546571/57106564-445dfc00-6d1d-11e9-87ff-354dd11f078a.png)

![T_wind_2D_WAM_jdel8_compiler_20150317_4p_cb](https://user-images.githubusercontent.com/22546571/57106597-58096280-6d1d-11e9-91f4-9597e8c4d05c.png)

![T_wind_2D_WAM_new_Weimer_swden_20150318_4p](https://user-images.githubusercontent.com/22546571/57106614-65bee800-6d1d-11e9-9183-d3db35c21aec.png)

![T_wind_2D_WAM_jdel8_compiler_20150318_4p_cb](https://user-images.githubusercontent.com/22546571/57106621-6b1c3280-6d1d-11e9-8fd4-42407903ad00.png)

**Comment by ZhuxiaoLi66** [comment]
Thanks for everyone's great inputs!

**Comment by akubaryk** [comment]
Are we able to run through the storm with a longer timestep? Results look great.

**Comment by ZhuxiaoLi66** [comment]
Just submitted a test job for 180s timestep. the current one is 60s. since the Temp. become mild now, maybe survive. Tim said once that we will move to the 60s anyway, forgot the reason, will double check.

**Comment by ZhuxiaoLi66** [comment]
Adam, Could you please help me to output ed1, ed2 and potent in efield.f in new_weimer branch? it is output of the subroutine DerivPotential in efield.f. I would like to do some tests and comparison with my individual efield.f to get some clue.

**Comment by akubaryk** [comment]
Sure, will try to have a separate branch available by tomorrow.

**Comment by ZhuxiaoLi66** [comment]
Thanks in ahead, that will be great. Haven't find any doubtful point by code checking.

**Comment by ZhuxiaoLi66** [comment]
By the way, what will be the output frequency? could be every timestep or mean over some period?

**Comment by akubaryk** [comment]
Would be every timestep (or can be done every n-timesteps for arbitrary n). Time-averaging is easiest to do in post-processing.

**Comment by akubaryk** [comment]
`new_weimer_netcdf` has been pushed up, you can check out the code and compile/run like normal. Like previous versions of this netcdf stuff, dtrad.nc4 will be in the RUNDIR with by-timestep output. I think it's on the same grid at efield.f? Simply set the lons from 0-360 by 2 and the lats from 90 to -90 by 2, but I could definitely have the ordering wrong, especially of the latitudes.

Let me know if you have any questions.

**Comment by ZhuxiaoLi66** [comment]
The bug has been found when the line of calling old SetModel is marked in the individual efield.f. So Adam, please take your time to make the output path for potent, ed1 and ed2.  Good weekend.

**Comment by ZhuxiaoLi66** [comment]
The following is the ed1 & ed2 fields by Weimer2005 in efield.f for Mark_old_SetModel test. 
![ED1_ED2_Weimer2005_efield_mark_SetM_test](https://user-images.githubusercontent.com/22546571/57559565-fb87f200-7371-11e9-8d98-fabc2c24c06a.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the electric potential fields by Weimer2005 in efield.f for Mark_old_SetModel test.
We can see the Electric Potential field changed very reasonable lightly before and after the Mark of the old SetModel module and after each subroutine in both of the cases. 

Epot before Mark the old SetModel module. 
![EPOT_new41_each_sub](https://user-images.githubusercontent.com/22546571/57637157-37050500-759a-11e9-9269-2abb73273b43.png)

Epot after Mark the old SetModel module. 
![EPOT_new41m_efield_each_sub](https://user-images.githubusercontent.com/22546571/57637209-56039700-759a-11e9-8a95-17806947e611.png)

**Comment by ZhuxiaoLi66** [comment]
T_U_V_2D plot on 20150317 based on the new WAM output.  
![T_2D_new_Weimer_mark_SetModel_20150317](https://user-images.githubusercontent.com/22546571/57645884-cf0ce980-75ae-11e9-85a8-ad554668501f.png)

**Comment by ZhuxiaoLi66** [comment]
The By= 0 problem seems solved by the calling of the whole new weimer package. 
The following plots are the ED1 & ED2 fields produced by the old Weimer and new Weimer called by the efield.f, when By= 0, Bz=1.77. 

![ED1 ED2_Weimer_1996_2005_new1bnd_efield](https://user-images.githubusercontent.com/22546571/58037763-ab512280-7b1d-11e9-81b1-84372285000a.png)

**Comment by ZhuxiaoLi66** [comment]
![T_2D_new_weimer_20130316](https://user-images.githubusercontent.com/22546571/58193838-81316900-7cb3-11e9-8a34-87ac00b3fa4c.png)

![T_wind_jdel8_WAM_LEV135_Mar16](https://user-images.githubusercontent.com/22546571/58193919-af16ad80-7cb3-11e9-8427-7c335832e022.png)

**Comment by ZhuxiaoLi66** [comment]
Latitudinal structure of T difference between weimer2005_swden and jdel8_dev_dip for 20130301-0315. 
![T_201303_weimer2005_jdel8_msis](https://user-images.githubusercontent.com/22546571/58270969-860d2000-7d7a-11e9-9508-a6603ab6d722.png)

![T_201303_weimer2005_jdel8_msis](https://user-images.githubusercontent.com/22546571/58270970-86a5b680-7d7a-11e9-9469-955e9db1c687.png)
