### ISSUE TITLE
Verification weimer2005 (swden) .vs. old weimer in WAM against the satellite data

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/WAM-IPE#296]
The new Weimer (2005) has been plugged in WAM with the extra input driving parameter 'swden'. Recently, with Martin's great works, Tim, Martin and I are grouped to do the verification of the two version Weimer against the GOCE and GRACE satellite data. We are investigating two storm cases, the 2013 (GOCE) and 2015 (GRACE) St. Patrick storm. Based on the current results, we would like to say the new weimer makes the total number density at about 410km (Grace track height) during 2015 St. Patrick storm time (Mar.17-18) down to a much more reasonable amplitude although still has kind of higher density compared with the Grace data. 

The details of the ongoing verification, further experiments and checking & adjustment will be posted here.

**Comment by ZhuxiaoLi66** [comment]
Here is Martin's validation works on 2015 St. Patrick storm. 
[del8_WAM.docx](https://github.com/SWPC-IPE/WAM-IPE/files/3248877/del8_WAM.docx)
[2015_Weimer_WAM.docx](https://github.com/SWPC-IPE/WAM-IPE/files/3248878/2015_Weimer_WAM.docx)
![old_weimer_2015_storm](https://user-images.githubusercontent.com/22546571/58824430-94d1bd80-862b-11e9-8841-8e72256ba511.png)
![Weimer2005_2015_storm_grace](https://user-images.githubusercontent.com/22546571/58824450-9f8c5280-862b-11e9-8739-72295404d363.png)

**Comment by ZhuxiaoLi66** [comment]
Here is Martin's validation work on 2013 St. Patrick storm,
![2013_st_patrick_storm_GOCE_weimer2005](https://user-images.githubusercontent.com/22546571/58824766-63a5bd00-862c-11e9-8131-0e4175102a74.png)
![2013_st_patrick_storm_GOCE_weimer2005](https://user-images.githubusercontent.com/22546571/58824788-73bd9c80-862c-11e9-9883-e2e18ab3778f.png)
![old_weimer_GOCE_2013_storm](https://user-images.githubusercontent.com/22546571/58824969-e9c20380-862c-11e9-995f-56e2efba473e.png)

**Comment by ZhuxiaoLi66** [comment]
For the further investigation on the higher total number density on Mar.17-18 2015, we checked the input driving parameters for both 2015 and 2013 St. Patrick storm period. A run with swden=5 for 2015 storm case has conducted and the output are processing. we would like to check the dependency of number density on swden.   

the following are some inputs for the two storm. 
![SW_Den_two_storms_date_5days](https://user-images.githubusercontent.com/22546571/58825512-23473e80-862e-11e9-9621-d94c67d3e1a0.png)
![Kp_2_storms_5days](https://user-images.githubusercontent.com/22546571/58825556-41ad3a00-862e-11e9-9dc7-6880d6fd2260.png)
![Bz_2_storms_5days](https://user-images.githubusercontent.com/22546571/58825583-4e319280-862e-11e9-99eb-b11a275548f3.png)
![SW_Vel_2_storms_5days](https://user-images.githubusercontent.com/22546571/58825612-5a1d5480-862e-11e9-806a-7129049face7.png)

**Comment by ZhuxiaoLi66** [comment]
The following for the longer period Mar1-20 for both 2013 and 2015. 
![F107_two_storms_date](https://user-images.githubusercontent.com/22546571/58825864-e2035e80-862e-11e9-8b76-a31ff14b15c1.png)
![Kp_two_storms_date](https://user-images.githubusercontent.com/22546571/58825897-f182a780-862e-11e9-85d7-045c9ebce88f.png)
![SW_Den_two_storms_date](https://user-images.githubusercontent.com/22546571/58825913-f8111f00-862e-11e9-8543-13d62852bbae.png)
![SW_Bt_two_storms_date](https://user-images.githubusercontent.com/22546571/58825933-00695a00-862f-11e9-90f4-5d443b4e4856.png)
![SW_Vel_two_storms_date](https://user-images.githubusercontent.com/22546571/58825952-0b23ef00-862f-11e9-8e29-4936360f893a.png)

**Comment by ZhuxiaoLi66** [comment]
Hi Adam, would like to ask your help on the 'fixall' run issue in my e-mail yesterday as following. 
 
I plan to do a driving parameters 'fixall' WAM standalone run. would like to double check with you the setting options  for parameters in the user.config files,  
# if you are using fixderive or fixall, uncomment the following and set your fixed values
 export FIX_F107=120.0     # F10.7 and F10.7d
 export FIX_KP=3.0         # Kp and 24hr average Kp
 export FIX_SWBT=1.0       # total solar wind
 export FIX_SWANG=0.0      # solar wind angle
 export FIX_SWVEL=400.0    # solar wind velocity
 export FIX_SWBZ=1.0       # z-component of solar wind
 export FIX_GWATTS=4.5     # gigawatts
 export FIX_HPI=2          # hemispheric power index
are these enough? it seems have 4 variables NHemiPow, NHemiPowIdx,    SHemiPow SHemiPowIdx about the 'hemisphere power' in your wam_input_f107_kp.txt file. 

I submitted a test run with the 'fixall' option, and the above setting, I got some error message in 
/scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/PTMP/swden_weimer2005_fixall_20130301_60s_1day/
fcst.806550

The run script is in:
/scratch3/NCEPDEV/swpc/save/Zhuxiao.Li/git/WAM-IPE_swden_2/scripts/compsets/user.config_20130301_fix_swden_60s

**Comment by akubaryk** [comment]
FIX_GWATTS and FIX_HPI are used for NHemiPow/SHemiPow and NHemiPowIdx/SHemiPowIdx respectively -- they are simply duplicated values for each hemisphere at the moment. The script seems to not have FIX_SWBZ based on the fcst.806550 file, which I don't understand exactly because it is in the user.config file. Going to run a test now.

**Comment by akubaryk** [comment]
Oops -- it's the $FIX_SWDEN variable instead. While I added that functionality to the branch, I forgot to put it in the example user.config files. Simply add that value to the user.config you are using and it will work.

**Comment by ZhuxiaoLi66** [comment]
Adam, it does works after adding FIX_SWDEN, and I checked the wam_input_f107_kp.txt, the parameters looks great, thanks!

**Comment by ZhuxiaoLi66** [comment]
the WAM run with 'fixall' option in run script seems too warm.  

![fixall_run_20130301_15](https://user-images.githubusercontent.com/22546571/60041944-0c838d00-96ac-11e9-8374-fbadace7f7ca.png)

**Comment by ZhuxiaoLi66** [comment]
Martin's validation plots for the Apr 5-7 2010 storm run, we don't know the reason, while the difference seems pretty large for the comparison of the WAM output with each satellite (GRACE, CHAMP and GOCE).  
[Normalized_2010Results.docx](https://github.com/SWPC-IPE/WAM-IPE/files/3322081/Normalized_2010Results.docx)

**Comment by ZhuxiaoLi66** [comment]
![GOCE_20100405_07](https://user-images.githubusercontent.com/22546571/60042740-f5459f00-96ad-11e9-8dfc-d194a0601e20.png)

**Comment by timfullerrowell** [comment]
Zhuziao,
Is this the annual run with 1.25 as the JH_factor?
Still a bit hot?

Did the new April run with 1.25 go through?
Tim

**Comment by ZhuxiaoLi66** [comment]
Here is the result for the new JH_factor of 1.25 + ...
The result seems too cold and flat. 
 
![GOCE_20100405-07_JH](https://user-images.githubusercontent.com/22546571/60458892-48c86780-9c2f-11e9-93cd-0c43289140c3.png)
