### ISSUE TITLE
Northern and Southern Top Index Arrays in IPE Grid

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-SWPC/WAM-IPE#318]
In `IPE_Grid_Class` method `Calculate_Grid_Attributes_From_Legacy_Input`, both `northern_top_index` and `southern_top_index` are computed based on the following hardcoded value of `mesh_height_max`:
https://github.com/SWPC-IPE/WAM-IPE/blob/b7a0df805154a06d4fc3bf4ab7f98439a80af233/IPELIB/src/IPE_Constants_Dictionary.F90#L18

However, `mesh_height_min` and `mesh_height_max` are input parameters, provided at runtime via the `&ipecap` namelist in `IPE.inp`.

The role of those arrays throughout the IPE code is unclear. Their values are also read from a NetCDF grid file.

This situation could lead to grave inconsistencies at runtime. We should discuss the role of such arrays and modify IPE's design accordingly.

**Comment by gmillward** [comment]
Calculate_Grid_Attributes_From_Legacy_Input just generates a grid.nc file from the legacy binary files that Naomi originally used. It's not used in IPE - it just resides in an IPE class.

**Comment by rmontuoro** [comment]
True, but `northern_top_index` and `southern_top_index` are used at runtime by IPE to update neutral arrays at each coupling time step in `Copy_WAM_to_IPE_CouplingFields` subroutine.

**Comment by rmontuoro** [comment]
Commits 950ba1d6 and 2f2d684d introduce a new `Initialize()` method to IPE `Grid` class.
This method needs to be called after reading in the IPE grid to recompute `northern_top_index`, `southern_top_index`, and `flux_tube_midpoint` arrays based on the input value of `mesh_height_max`.

**Comment by rmontuoro** [comment]
Issue resolved.
