### ISSUE TITLE
occasional crashing with new GSI on Phase 3

### ISSUE THREAD

**Issue by akubaryk** [NOAA-SWPC/WAM-IPE#341]
@wanghj2015 has issues to report with occasional MPI-related crashes with the new GSI on Phase 3.

**Comment by wanghj2015** [comment]
The error messages are as follows:

v53c71.ncep.noaa.gov:UCM:18239:cd23700: 413504226 us(413504226 us!!!): UCM connect: REQ RETRIES EXHAUSTED: 0x246 c21e 0x183 -> 0x283 2e4aa 0x2b58
[68:v53c71f] unexpected DAPL connection event 0x4008 from 83
Fatal error in PMPI_Alltoallv: Internal MPI error!, error stack:
PMPI_Alltoallv(665)......: MPI_Alltoallv(sbuf=0x7ffff9817780, scnts=0x2b370f0ba780, sdispls=0x2b370e761800, dtype=0x4c000829, rbuf=0x7ffff97a6810, rcnts=0x2b370f0ba400, rdispls=0x2b370e761400, dtype=0x4c000829, MPI_COMM_WORLD) failed
MPIR_Alltoallv_impl(416).: fail failed
MPIR_Alltoallv(373)......: fail failed
MPIR_Alltoallv_intra(226): fail failed
MPIR_Waitall_impl(221)...: fail failed
PMPIDI_CH3I_Progress(850): fail failed
(unknown)(): Internal MPI error!

It happened occasionally before, and runs continue after resubmit. 

I submitted a request for help to 'wcoss-helpdesk@noaa.gov' on April 26 2019 when it happened last time, but I haven't got any response. There are some suggestions on solving the problem online, e.g.,

https://www.dkrz.de/up/help/known-issues
https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/289963

But I haven't actually tried these suggestions yet.
